public enum MedicalSpecializzation {
    CARDIOLOGY,
    DERMATOLOGY,
    ENDOCRINOLOGY,
    GASTROENTOROLOGY,
    NEUROLOGY,
    PULMUNOLOGY,
    UROLOGY,
    RHEUMATOLOGY,
    ORTHOPAEDICS,
    RADIOLOGY
}
